# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NextSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'GoogleMaps'
pod 'RealmSwift'

  # Pods for NextSwift

  target 'NextSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NextSwiftUITests' do
    # Pods for testing
  end

end
